package responses;

public enum Status {
	USER_SUCCESSFULLY_CREATED,
	USER_SUCCESSFULLY_LOGGEDIN,
	USER_LOGOUT_SUCCESS,
	DO_SOMETHING_SUCCESS,
	
	AUTHORIZATION_ERROR,
	DB_ERROR,
	USERNAME_ERROR,
	PASSWORD_ERROR,
	NOT_FOUND_ERROR
}
